#specifies Events, Jobs,Runners, Steps, Actions
# Event- trigger for a workflow
# 
name: Cypress Tests

#Trigger - pushed to repo  
on:  
  push: 
    #branches:
     # -'feat/Testing_pipeline'
jobs:
  set-up:
    runs-on: ubuntu-latest

    # Checks repo, pulls in the pipeline 
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

     # Sets up Node
    - name: Use Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn cache clean
      run: yarn install

    # Installs our dependencies
    - name: Cypress run 
      uses: cypress-io/github-action@v3
      with:
       # repository: itech-it1i-gruppe6/EasyNote
        #repo-token: ${{ secrets.GITHUB_TOKEN }}
        build: yarn build
        start: yarn start

      
  




